name: Development Build

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - feature
      - bugfix
      - support
  pull_request:
    branches:
      - develop
      - feature
      - bugfix
      - support

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "Mako"
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_LOGO: false
  BUILD_CONFIGURATION: "Debug"
  DOTNET_VERSION: "6.x"

jobs:
  build-job:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: "1.0.0"
    outputs:
      output1: ${{ steps.get-version-step.outputs.app-version }}
      output2: ${{ steps.get-date-step.outputs.build-date }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: get-version-step
        run: echo "app-version=$APP_VERSION.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - id: get-date-step
        run: echo "build-date=$(date +'%Y-%m-%d:%T')" >> $GITHUB_OUTPUT

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Show APP_VERSION
        run: echo APP_VERSION ${{needs.build-job.outputs.output1}}

      - name: Show Build Date
        run: echo Build Date ${{needs.build-job.outputs.output2}}

      - name: Create info json file
        uses: devops-actions/json-to-file@v1.0.1
        with:
          json: '{"version":"${{needs.build-job.outputs.output1}}"}'
          filename: "version.json"

      - name: Build and package
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration '${{ env.BUILD_CONFIGURATION }}' /p:DeployOnBuild=true /p:DeployTarget=Package;CreatePackageOnPublish=true
          popd

#       - name: Upload Artifact
#         uses: actions/upload-artifact@v3.1.1
#         with:
#           name: mako
#           path: ${{ github.workspace }}
#           retention-days: 30
