name: Development Build

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "Mako"
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_LOGO: false
  BUILD_CONFIGURATION: "Debug"
  DOTNET_VERSION: "6.x"

jobs:
  init-job:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: "1.0.0"
    outputs:
      output1: ${{ steps.get-version-step.outputs.app-version }}
      output2: ${{ steps.get-date-step.outputs.build-date }}
      output3: ${{ steps.get-repository-name-step.outputs.repository-name }}
      output4: ${{ steps.get-branch-name-step.outputs.branch-name }}
      output5: ${{ steps.get-builder-step.outputs.builder-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: get-version-step
        run: echo "app-version=${{ env.APP_VERSION }}.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - id: get-date-step
        run: echo "build-date=$(date +'%Y-%m-%d:%T')" >> $GITHUB_OUTPUT

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - uses: FranzDiebold/github-env-vars-action@v2.7.0
      - id: get-repository-name-step
        run: echo "repository-name=$CI_REPOSITORY_NAME" >> $GITHUB_OUTPUT
      - id: get-branch-name-step
        run: echo "branch-name=$CI_REF_NAME" >> $GITHUB_OUTPUT
      - id: get-builder-step
        run: echo "builder-name=$CI_ACTOR" >> $GITHUB_OUTPUT
      
          
  build-job:
    runs-on: ubuntu-latest
    needs: init-job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show APP_VERSION
        run: echo APP_VERSION ${{needs.init-job.outputs.output1}}

      - name: Show Build Date
        run: echo Build Date ${{needs.init-job.outputs.output2}}

      - name: Create version json file
        uses: devops-actions/json-to-file@v1.0.1
        with:
          json: '{"app_version": "${{needs.init-job.outputs.output1}}", "build_run": "${{ github.run_number }}", "build_commit_hash": "${{ GITHUB.SHA }}", "build_branch": "${{needs.init-job.outputs.output4}}", "build_date": "${{needs.init-job.outputs.output2}}", "repository": "${{needs.init-job.outputs.output3}}", "built_by": "${{needs.init-job.outputs.output5}}"}'
          filename: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/version.json"

      - name: GitHub Action for committing changes to a repository
        uses: devops-infra/action-commit-push@v0.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Update version

      - name: Build and package
        shell: bash
        run: |
          echo Path ${{ github.workspace }}
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration '${{ env.BUILD_CONFIGURATION }}' /p:DeployOnBuild=true /p:DeployTarget=Package;CreatePackageOnPublish=true
          popd

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: mako-${{needs.init-job.outputs.output1}}
          path: ${{ github.workspace }}/Mako/obj/${{ env.BUILD_CONFIGURATION }}/net6.0/PubTmp/Out/
          retention-days: 10

