name: Development Build

on:
  workflow_dispatch:
#   push:
#     branches:
#       - develop
#       - feature
#       - bugfix
#       - support
#   pull_request:
#     branches:
#       - develop
#       - feature
#       - bugfix
#       - support

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "Mako"
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_LOGO: false
  BUILD_CONFIGURATION: "Debug"
  DOTNET_VERSION: "6.x"

jobs:
  init-job:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: "1.0.0"
    outputs:
      output1: ${{ steps.get-version-step.outputs.app-version }}
      output2: ${{ steps.get-date-step.outputs.build-date }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: get-version-step
        run: echo "app-version=${{ env.APP_VERSION }}.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - id: get-date-step
        run: echo "build-date=$(date +'%Y-%m-%d:%T')" >> $GITHUB_OUTPUT

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - uses: FranzDiebold/github-env-vars-action@v2.7.0
      - name: GitHub Environment Variables Action
        run: |
          echo "CI_REPOSITORY_SLUG=$CI_REPOSITORY_SLUG"
          echo "CI_REPOSITORY_OWNER=$CI_REPOSITORY_OWNER"
          echo "CI_REPOSITORY_OWNER_SLUG=$CI_REPOSITORY_OWNER_SLUG"
          echo "CI_REPOSITORY_NAME=$CI_REPOSITORY_NAME"
          echo "CI_REPOSITORY_NAME_SLUG=$CI_REPOSITORY_NAME_SLUG"
          echo "CI_REPOSITORY=$CI_REPOSITORY"
          echo "CI_REF_SLUG=$CI_REF_SLUG"
          echo "CI_ACTION_REF_NAME=$CI_ACTION_REF_NAME"
          echo "CI_ACTION_REF_NAME_SLUG=$CI_ACTION_REF_NAME_SLUG"
          echo "CI_REF_NAME=$CI_REF_NAME"
          echo "CI_REF_NAME_SLUG=$CI_REF_NAME_SLUG"
          echo "CI_REF=$CI_REF"
          echo "CI_HEAD_REF_SLUG=$CI_HEAD_REF_SLUG"
          echo "CI_HEAD_REF=$CI_HEAD_REF"
          echo "CI_BASE_REF_SLUG=$CI_BASE_REF_SLUG"
          echo "CI_BASE_REF=$CI_BASE_REF"
          echo "CI_SHA_SHORT=$CI_SHA_SHORT"
          echo "CI_SHA=$CI_SHA"
          echo "CI_PR_SHA_SHORT=$CI_PR_SHA_SHORT"
          echo "CI_PR_SHA=$CI_PR_SHA"
          echo "CI_PR_NUMBER=$CI_PR_NUMBER"
          echo "CI_PR_ID=$CI_PR_ID"
          echo "CI_PR_TITLE=$CI_PR_TITLE"
          echo "CI_PR_DESCRIPTION=$CI_PR_DESCRIPTION"
          echo "CI_ACTOR=$CI_ACTOR"
          echo "CI_EVENT_NAME=$CI_EVENT_NAME"
          echo "CI_RUN_ID=$CI_RUN_ID"
          echo "CI_RUN_NUMBER=$CI_RUN_NUMBER"
          echo "CI_WORKFLOW=$CI_WORKFLOW"
          echo "CI_ACTION=$CI_ACTION"

  build-job:
    runs-on: ubuntu-latest
    needs: init-job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show APP_VERSION
        run: echo APP_VERSION ${{needs.init-job.outputs.output1}}

      - name: Show Build Date
        run: echo Build Date ${{needs.init-job.outputs.output2}}

      - name: Create version json file
        uses: devops-actions/json-to-file@v1.0.1
        with:
          json: '{"app_version": "${{needs.init-job.outputs.output1}}", "build_run": "${{ github.run_number }}", "build_commit_hash": "${{ GITHUB.SHA }}", "build_branch": "${{ GITHUB.REF }}", "build_date": "${{needs.init-job.outputs.output2}}"}'
          filename: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/version.json"

      - name: GitHub Action for committing changes to a repository
        uses: devops-infra/action-commit-push@v0.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Update version

      - name: Build and package
        shell: bash
        run: |
          echo Path ${{ github.workspace }}
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration '${{ env.BUILD_CONFIGURATION }}' /p:DeployOnBuild=true /p:DeployTarget=Package;CreatePackageOnPublish=true
          popd

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: mako-${{needs.init-job.outputs.output1}}
          path: ${{ github.workspace }}/Mako/obj/${{ env.BUILD_CONFIGURATION }}/net6.0/PubTmp/Out/
          retention-days: 10

